/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HOSPITAL_H_RPCGEN
#define _HOSPITAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct init_data {
	int num_quirofano;
	int num_equipo;
};
typedef struct init_data init_data;

struct recursos {
	int key_quirofanos;
	int key_equipos;
};
typedef struct recursos recursos;

#define HOSPITAL 400000073
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define inicializar_hospital 1
extern  int * inicializar_hospital_1(init_data *, CLIENT *);
extern  int * inicializar_hospital_1_svc(init_data *, struct svc_req *);
#define reservar_quirofano 2
extern  int * reservar_quirofano_1(int *, CLIENT *);
extern  int * reservar_quirofano_1_svc(int *, struct svc_req *);
#define reservar_equipo_enfermeria 3
extern  int * reservar_equipo_enfermeria_1(int *, CLIENT *);
extern  int * reservar_equipo_enfermeria_1_svc(int *, struct svc_req *);
#define liberar_recursos 4
extern  int * liberar_recursos_1(recursos *, CLIENT *);
extern  int * liberar_recursos_1_svc(recursos *, struct svc_req *);
extern int hospital_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define inicializar_hospital 1
extern  int * inicializar_hospital_1();
extern  int * inicializar_hospital_1_svc();
#define reservar_quirofano 2
extern  int * reservar_quirofano_1();
extern  int * reservar_quirofano_1_svc();
#define reservar_equipo_enfermeria 3
extern  int * reservar_equipo_enfermeria_1();
extern  int * reservar_equipo_enfermeria_1_svc();
#define liberar_recursos 4
extern  int * liberar_recursos_1();
extern  int * liberar_recursos_1_svc();
extern int hospital_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_init_data (XDR *, init_data*);
extern  bool_t xdr_recursos (XDR *, recursos*);

#else /* K&R C */
extern bool_t xdr_init_data ();
extern bool_t xdr_recursos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HOSPITAL_H_RPCGEN */
